export const COINGECKO_IDS = {
  BTC: "bitcoin",
  ETH: "ethereum",
  BNB: "binancecoin",
  SOL: "solana",
  XRP: "ripple",
  ADA: "cardano",
  DOGE: "dogecoin",
  AVAX: "avalanche-2",
  LINK: "chainlink"
};
// 주의: Binance는 USDT 기준가를 반환함. USDT는 통상 1달러에 근접하나 완전히 동일하지는 않음.
export const BINANCE_SYMBOLS = {
  BTC: "BTCUSDT",
  ETH: "ETHUSDT",
  SOL: "SOLUSDT",
  XRP: "XRPUSDT",
  ADA: "ADAUSDT",
  DOGE: "DOGEUSDT",
  AVAX: "AVAXUSDT",
  LINK: "LINKUSDT",
  BNB: "BNBUSDT"
};
export const CRYPTO_LOGOS = {
  BTC: "https://cdn.simpleicons.org/bitcoin/f7931a",
  ETH: "https://cdn.simpleicons.org/ethereum/627eea",
  SOL: "https://cdn.simpleicons.org/solana/9945ff",
  BNB: "https://cdn.simpleicons.org/binance/f3ba2f",
  XRP: "https://cdn.simpleicons.org/xrp/f3f3f7"
};
export const DIVIDEND_MONTHS = {
  SCHD: [3, 6, 9, 12],
  O: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  "360750": [1, 4, 7, 10],
  KR3Y: [3, 6, 9, 12]
};
export const INDEX_MONITOR_LIST = [
  { ticker: "QQQ", label: "나스닥", group: "ETF", logoText: "Q" },
  { ticker: "SPY", label: "S&P500", group: "ETF", logoText: "S&P" },
  { ticker: "IWM", label: "러셀2000", group: "ETF", logoText: "R2K" },
  { ticker: "SOXX", label: "필라델피아 반도체", group: "ETF", logoText: "SOX" },
  { ticker: "AAPL", label: "Apple", group: "M7", logo: "https://cdn.simpleicons.org/apple/f3f3f7" },
  { ticker: "MSFT", label: "Microsoft", group: "M7", logo: "https://cdn.simpleicons.org/microsoft/f3f3f7" },
  { ticker: "GOOGL", label: "Alphabet", group: "M7", logo: "https://cdn.simpleicons.org/google/f3f3f7" },
  { ticker: "AMZN", label: "Amazon", group: "M7", logo: "https://cdn.simpleicons.org/amazon/f3f3f7" },
  { ticker: "NVDA", label: "NVIDIA", group: "M7", logo: "https://cdn.simpleicons.org/nvidia/f3f3f7" },
  { ticker: "META", label: "Meta", group: "M7", logo: "https://cdn.simpleicons.org/meta/f3f3f7" },
  { ticker: "TSLA", label: "Tesla", group: "M7", logo: "https://cdn.simpleicons.org/tesla/f3f3f7" }
];
export const ASSET_DICTIONARY = [
  { ticker: "AAPL", name: "Apple", type: "주식", currency: "USD" },
  { ticker: "MSFT", name: "Microsoft", type: "주식", currency: "USD" },
  { ticker: "NVDA", name: "NVIDIA", type: "주식", currency: "USD" },
  { ticker: "AMZN", name: "Amazon", type: "주식", currency: "USD" },
  { ticker: "GOOGL", name: "Alphabet", type: "주식", currency: "USD" },
  { ticker: "META", name: "Meta Platforms", type: "주식", currency: "USD" },
  { ticker: "TSLA", name: "Tesla", type: "주식", currency: "USD" },
  { ticker: "AVGO", name: "Broadcom", type: "주식", currency: "USD" },
  { ticker: "BRK.B", name: "Berkshire Hathaway", type: "주식", currency: "USD" },
  { ticker: "LLY", name: "Eli Lilly", type: "주식", currency: "USD" },
  { ticker: "JPM", name: "JPMorgan Chase", type: "주식", currency: "USD" },
  { ticker: "V", name: "Visa", type: "주식", currency: "USD" },
  { ticker: "MA", name: "Mastercard", type: "주식", currency: "USD" },
  { ticker: "WMT", name: "Walmart", type: "주식", currency: "USD" },
  { ticker: "XOM", name: "Exxon Mobil", type: "주식", currency: "USD" },
  { ticker: "UNH", name: "UnitedHealth Group", type: "주식", currency: "USD" },
  { ticker: "COST", name: "Costco Wholesale", type: "주식", currency: "USD" },
  { ticker: "HD", name: "Home Depot", type: "주식", currency: "USD" },
  { ticker: "PG", name: "Procter & Gamble", type: "주식", currency: "USD" },
  { ticker: "JNJ", name: "Johnson & Johnson", type: "주식", currency: "USD" },
  { ticker: "ABBV", name: "AbbVie", type: "주식", currency: "USD" },
  { ticker: "NFLX", name: "Netflix", type: "주식", currency: "USD" },
  { ticker: "CRM", name: "Salesforce", type: "주식", currency: "USD" },
  { ticker: "ORCL", name: "Oracle", type: "주식", currency: "USD" },
  { ticker: "AMD", name: "Advanced Micro Devices", type: "주식", currency: "USD" },
  { ticker: "BAC", name: "Bank of America", type: "주식", currency: "USD" },
  { ticker: "KO", name: "Coca-Cola", type: "주식", currency: "USD" },
  { ticker: "PEP", name: "PepsiCo", type: "주식", currency: "USD" },
  { ticker: "MCD", name: "McDonald's", type: "주식", currency: "USD" },
  { ticker: "CSCO", name: "Cisco Systems", type: "주식", currency: "USD" },
  { ticker: "TMO", name: "Thermo Fisher Scientific", type: "주식", currency: "USD" },
  { ticker: "LIN", name: "Linde", type: "주식", currency: "USD" },
  { ticker: "ADBE", name: "Adobe", type: "주식", currency: "USD" },
  { ticker: "WFC", name: "Wells Fargo", type: "주식", currency: "USD" },
  { ticker: "DIS", name: "Walt Disney", type: "주식", currency: "USD" },
  { ticker: "INTU", name: "Intuit", type: "주식", currency: "USD" },
  { ticker: "IBM", name: "IBM", type: "주식", currency: "USD" },
  { ticker: "GE", name: "GE Aerospace", type: "주식", currency: "USD" },
  { ticker: "CAT", name: "Caterpillar", type: "주식", currency: "USD" },
  { ticker: "QCOM", name: "Qualcomm", type: "주식", currency: "USD" },
  { ticker: "TXN", name: "Texas Instruments", type: "주식", currency: "USD" },
  { ticker: "AMAT", name: "Applied Materials", type: "주식", currency: "USD" },
  { ticker: "NOW", name: "ServiceNow", type: "주식", currency: "USD" },
  { ticker: "ISRG", name: "Intuitive Surgical", type: "주식", currency: "USD" },
  { ticker: "VZ", name: "Verizon", type: "주식", currency: "USD" },
  { ticker: "T", name: "AT&T", type: "주식", currency: "USD" },
  { ticker: "CMCSA", name: "Comcast", type: "주식", currency: "USD" },
  { ticker: "NKE", name: "Nike", type: "주식", currency: "USD" },
  { ticker: "PFE", name: "Pfizer", type: "주식", currency: "USD" },
  { ticker: "MRK", name: "Merck", type: "주식", currency: "USD" },
  { ticker: "SPY", name: "SPDR S&P 500 ETF", type: "ETF", currency: "USD" },
  { ticker: "QQQ", name: "Invesco QQQ Trust", type: "ETF", currency: "USD" },
  { ticker: "VOO", name: "Vanguard S&P 500 ETF", type: "ETF", currency: "USD" },
  { ticker: "IVV", name: "iShares Core S&P 500 ETF", type: "ETF", currency: "USD" },
  { ticker: "VTI", name: "Vanguard Total Stock Market ETF", type: "ETF", currency: "USD" },
  { ticker: "SCHD", name: "Schwab U.S. Dividend Equity ETF", type: "ETF", currency: "USD" },
  { ticker: "JEPI", name: "JPMorgan Equity Premium Income ETF", type: "ETF", currency: "USD" },
  { ticker: "JEPQ", name: "JPMorgan Nasdaq Equity Premium Income ETF", type: "ETF", currency: "USD" },
  { ticker: "QQQI", name: "NEOS Nasdaq-100 High Income ETF", type: "ETF", currency: "USD" },
  { ticker: "GPIX", name: "Goldman Sachs S&P 500 Core Premium Income ETF", type: "ETF", currency: "USD" },
  { ticker: "GPIQ", name: "Goldman Sachs Nasdaq-100 Core Premium Income ETF", type: "ETF", currency: "USD" },
  { ticker: "FEPI", name: "REX FANG & Innovation Equity Premium Income ETF", type: "ETF", currency: "USD" },
  { ticker: "DIVO", name: "Amplify CWP Enhanced Dividend Income ETF", type: "ETF", currency: "USD" },
  { ticker: "XYLD", name: "Global X S&P 500 Covered Call ETF", type: "ETF", currency: "USD" },
  { ticker: "QYLD", name: "Global X Nasdaq 100 Covered Call ETF", type: "ETF", currency: "USD" },
  { ticker: "RYLD", name: "Global X Russell 2000 Covered Call ETF", type: "ETF", currency: "USD" },
  { ticker: "TSLY", name: "YieldMax TSLA Option Income Strategy ETF", type: "ETF", currency: "USD" },
  { ticker: "NVDY", name: "YieldMax NVDA Option Income Strategy ETF", type: "ETF", currency: "USD" },
  { ticker: "CONY", name: "YieldMax COIN Option Income Strategy ETF", type: "ETF", currency: "USD" },
  { ticker: "MSTY", name: "YieldMax MSTR Option Income Strategy ETF", type: "ETF", currency: "USD" },
  { ticker: "YMAX", name: "YieldMax Universe Fund of Option Income ETFs", type: "ETF", currency: "USD" },
  { ticker: "YMAG", name: "YieldMax Magnificent 7 Fund of Option Income ETFs", type: "ETF", currency: "USD" },
  { ticker: "TSLL", name: "Direxion Daily TSLA Bull 2X Shares", type: "ETF", currency: "USD" },
  { ticker: "TSLQ", name: "AXS TSLA Bear Daily ETF", type: "ETF", currency: "USD" },
  { ticker: "NVDL", name: "GraniteShares 2x Long NVDA Daily ETF", type: "ETF", currency: "USD" },
  { ticker: "NVDU", name: "Direxion Daily NVDA Bull 2X Shares", type: "ETF", currency: "USD" },
  { ticker: "NVDS", name: "AXS 1.25X NVDA Bear Daily ETF", type: "ETF", currency: "USD" },
  { ticker: "AAPU", name: "Direxion Daily AAPL Bull 2X Shares", type: "ETF", currency: "USD" },
  { ticker: "MSFU", name: "Direxion Daily MSFT Bull 2X Shares", type: "ETF", currency: "USD" },
  { ticker: "GGLL", name: "Direxion Daily GOOGL Bull 2X Shares", type: "ETF", currency: "USD" },
  { ticker: "AMZU", name: "Direxion Daily AMZN Bull 2X Shares", type: "ETF", currency: "USD" },
  { ticker: "METU", name: "Direxion Daily META Bull 2X Shares", type: "ETF", currency: "USD" },
  { ticker: "CONL", name: "GraniteShares 2x Long COIN Daily ETF", type: "ETF", currency: "USD" },
  { ticker: "MSTU", name: "T-Rex 2X Long MSTR Daily Target ETF", type: "ETF", currency: "USD" },
  { ticker: "MSTX", name: "Defiance Daily Target 2X Long MSTR ETF", type: "ETF", currency: "USD" },
  { ticker: "TQQQ", name: "ProShares UltraPro QQQ", type: "ETF", currency: "USD" },
  { ticker: "SQQQ", name: "ProShares UltraPro Short QQQ", type: "ETF", currency: "USD" },
  { ticker: "QLD", name: "ProShares Ultra QQQ", type: "ETF", currency: "USD" },
  { ticker: "UPRO", name: "ProShares UltraPro S&P500", type: "ETF", currency: "USD" },
  { ticker: "SPXL", name: "Direxion Daily S&P 500 Bull 3X Shares", type: "ETF", currency: "USD" },
  { ticker: "SSO", name: "ProShares Ultra S&P500", type: "ETF", currency: "USD" },
  { ticker: "SPXU", name: "ProShares UltraPro Short S&P500", type: "ETF", currency: "USD" },
  { ticker: "UDOW", name: "ProShares UltraPro Dow30", type: "ETF", currency: "USD" },
  { ticker: "URTY", name: "ProShares UltraPro Russell2000", type: "ETF", currency: "USD" },
  { ticker: "TNA", name: "Direxion Daily Small Cap Bull 3X Shares", type: "ETF", currency: "USD" },
  { ticker: "SOXL", name: "Direxion Daily Semiconductor Bull 3X Shares", type: "ETF", currency: "USD" },
  { ticker: "SOXS", name: "Direxion Daily Semiconductor Bear 3X Shares", type: "ETF", currency: "USD" },
  { ticker: "TECL", name: "Direxion Daily Technology Bull 3X Shares", type: "ETF", currency: "USD" },
  { ticker: "TECS", name: "Direxion Daily Technology Bear 3X Shares", type: "ETF", currency: "USD" },
  { ticker: "FNGU", name: "MicroSectors FANG+ Index 3X Leveraged ETN", type: "ETF", currency: "USD" },
  { ticker: "FNGD", name: "MicroSectors FANG+ Index -3X Inverse Leveraged ETN", type: "ETF", currency: "USD" },
  { ticker: "LABU", name: "Direxion Daily S&P Biotech Bull 3X Shares", type: "ETF", currency: "USD" },
  { ticker: "FAS", name: "Direxion Daily Financial Bull 3X Shares", type: "ETF", currency: "USD" },
  { ticker: "ERX", name: "Direxion Daily Energy Bull 2X Shares", type: "ETF", currency: "USD" },
  { ticker: "YINN", name: "Direxion Daily FTSE China Bull 3X Shares", type: "ETF", currency: "USD" },
  { ticker: "WEBL", name: "Direxion Daily Dow Jones Internet Bull 3X Shares", type: "ETF", currency: "USD" },
  { ticker: "BITX", name: "Volatility Shares 2x Bitcoin ETF", type: "ETF", currency: "USD" },
  { ticker: "BITU", name: "ProShares Ultra Bitcoin ETF", type: "ETF", currency: "USD" },
  { ticker: "ETHU", name: "Volatility Shares 2x Ether ETF", type: "ETF", currency: "USD" },
  { ticker: "BOIL", name: "ProShares Ultra Bloomberg Natural Gas", type: "ETF", currency: "USD" },
  { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", type: "ETF", currency: "USD" },
  { ticker: "SHY", name: "iShares 1-3 Year Treasury Bond ETF", type: "ETF", currency: "USD" },
  { ticker: "IEF", name: "iShares 7-10 Year Treasury Bond ETF", type: "ETF", currency: "USD" },
  { ticker: "HYG", name: "iShares iBoxx High Yield Corporate Bond ETF", type: "ETF", currency: "USD" },
  { ticker: "LQD", name: "iShares iBoxx Investment Grade Corporate Bond ETF", type: "ETF", currency: "USD" },
  { ticker: "BND", name: "Vanguard Total Bond Market ETF", type: "ETF", currency: "USD" },
  { ticker: "AGG", name: "iShares Core U.S. Aggregate Bond ETF", type: "ETF", currency: "USD" },
  { ticker: "VNQ", name: "Vanguard Real Estate ETF", type: "ETF", currency: "USD" },
  { ticker: "GLD", name: "SPDR Gold Shares", type: "ETF", currency: "USD" },
  { ticker: "SLV", name: "iShares Silver Trust", type: "ETF", currency: "USD" },
  { ticker: "SOXX", name: "iShares Semiconductor ETF", type: "ETF", currency: "USD" },
  { ticker: "SMH", name: "VanEck Semiconductor ETF", type: "ETF", currency: "USD" },
  { ticker: "XLK", name: "Technology Select Sector SPDR Fund", type: "ETF", currency: "USD" },
  { ticker: "XLF", name: "Financial Select Sector SPDR Fund", type: "ETF", currency: "USD" },
  { ticker: "XLE", name: "Energy Select Sector SPDR Fund", type: "ETF", currency: "USD" },
  { ticker: "XLY", name: "Consumer Discretionary Select Sector SPDR Fund", type: "ETF", currency: "USD" },
  { ticker: "XLP", name: "Consumer Staples Select Sector SPDR Fund", type: "ETF", currency: "USD" },
  { ticker: "XLU", name: "Utilities Select Sector SPDR Fund", type: "ETF", currency: "USD" },
  { ticker: "XLI", name: "Industrial Select Sector SPDR Fund", type: "ETF", currency: "USD" },
  { ticker: "XLV", name: "Health Care Select Sector SPDR Fund", type: "ETF", currency: "USD" },
  { ticker: "ARKK", name: "ARK Innovation ETF", type: "ETF", currency: "USD" },
  { ticker: "069500", name: "KODEX 200", type: "ETF", currency: "KRW" },
  { ticker: "102110", name: "TIGER 200", type: "ETF", currency: "KRW" },
  { ticker: "133690", name: "TIGER 미국나스닥100", type: "ETF", currency: "KRW" },
  { ticker: "360750", name: "TIGER 미국S&P500", type: "ETF", currency: "KRW" },
  { ticker: "379800", name: "KODEX 미국S&P500TR", type: "ETF", currency: "KRW" },
  { ticker: "381180", name: "TIGER 미국필라델피아반도체나스닥", type: "ETF", currency: "KRW" },
  { ticker: "458730", name: "TIGER 미국배당다우존스", type: "ETF", currency: "KRW" },
  { ticker: "441640", name: "KODEX 미국배당프리미엄액티브", type: "ETF", currency: "KRW" },
  { ticker: "305540", name: "TIGER 2차전지테마", type: "ETF", currency: "KRW" },
  { ticker: "229200", name: "KODEX 코스닥150", type: "ETF", currency: "KRW" },
  { ticker: "KR3Y", name: "국고채 3년", type: "채권", currency: "KRW" },
  { ticker: "BTC", name: "Bitcoin", type: "코인", currency: "USD" },
  { ticker: "ETH", name: "Ethereum", type: "코인", currency: "USD" },
  { ticker: "SOL", name: "Solana", type: "코인", currency: "USD" },
  { ticker: "BNB", name: "BNB", type: "코인", currency: "USD" },
  { ticker: "XRP", name: "XRP", type: "코인", currency: "USD" },
  { ticker: "ADA", name: "Cardano", type: "코인", currency: "USD" },
  { ticker: "DOGE", name: "Dogecoin", type: "코인", currency: "USD" },
  { ticker: "AVAX", name: "Avalanche", type: "코인", currency: "USD" },
  { ticker: "LINK", name: "Chainlink", type: "코인", currency: "USD" },
  { ticker: "DOT", name: "Polkadot", type: "코인", currency: "USD" },
  { ticker: "MATIC", name: "Polygon", type: "코인", currency: "USD" },
  { ticker: "TON", name: "Toncoin", type: "코인", currency: "USD" },
  { ticker: "TRX", name: "TRON", type: "코인", currency: "USD" },
  { ticker: "LTC", name: "Litecoin", type: "코인", currency: "USD" },
  { ticker: "BCH", name: "Bitcoin Cash", type: "코인", currency: "USD" },
  { ticker: "UNI", name: "Uniswap", type: "코인", currency: "USD" },
  { ticker: "AAVE", name: "Aave", type: "코인", currency: "USD" },
  { ticker: "NEAR", name: "NEAR Protocol", type: "코인", currency: "USD" },
  { ticker: "ATOM", name: "Cosmos", type: "코인", currency: "USD" },
  { ticker: "FIL", name: "Filecoin", type: "코인", currency: "USD" },
  { ticker: "ICP", name: "Internet Computer", type: "코인", currency: "USD" },
  { ticker: "ETC", name: "Ethereum Classic", type: "코인", currency: "USD" },
  { ticker: "XLM", name: "Stellar", type: "코인", currency: "USD" },
  { ticker: "HBAR", name: "Hedera", type: "코인", currency: "USD" },
  { ticker: "APT", name: "Aptos", type: "코인", currency: "USD" },
  { ticker: "SUI", name: "Sui", type: "코인", currency: "USD" },
  { ticker: "ARB", name: "Arbitrum", type: "코인", currency: "USD" },
  { ticker: "OP", name: "Optimism", type: "코인", currency: "USD" },
  { ticker: "PEPE", name: "Pepe", type: "코인", currency: "USD" },
  { ticker: "SHIB", name: "Shiba Inu", type: "코인", currency: "USD" }
];
